{{- $fullName := include "vpconsumer-service.fullname" . -}}
{{- $labels := include "vpconsumer-service.labels" . }}
{{- $release := .Release.Namespace }}
{{ if .Values.autoscaling.keda.enabled }}
{{ $keda := .Values.autoscaling.keda }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-hpa-{{ $fullName }}
  namespace: {{ $release }}
  labels:
spec:
  scaleTargetRef:
    name: {{ $fullName }}
  pollingInterval: {{ $keda.pollingInterval }}
  cooldownPeriod:  {{ $keda.cooldownPeriod }}
  minReplicaCount: {{ $keda.minReplicaCount }}
  maxReplicaCount: {{ $keda.maxReplicaCount }}
  {{ with $keda.triggers }}
  triggers:
  {{- toYaml . | nindent 2 }}
  {{ end}}
{{- end }}