{{- $fullName := include "vpconsumer-service.fullname" . -}}

{{ if .Values.argo.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{ else }}
apiVersion: apps/v1
kind: Deployment
{{ end }}
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpconsumer-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
 {{ if .Values.argo.enabled }}
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService: 
            name: ivs-{{ $fullName }}
            routes:
            - canary-rollout
          destinationRule:
            name: dstr-{{ $fullName }}
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
        # for initial step in support of canary-testing (via header) with NO public traffic yet because of scale without weight
        - setCanaryScale:
            replicas: 1 # a team may set this higher if smoke tests during canary-testing do any checks where load needs more than 1
        - pause: {} # canary testing for promote vs rollback should happen here
        # If all canary-testing passed then we can proceed with remaining steps based on percentages
        - setCanaryScale:
            weight: 25 # set initial canary traffic weight
            matchTrafficWeight: true # returns to the default behavior of matching the canary traffic weight
        - pause: { duration: 30s }
        - setCanaryScale:
            weight: 50 # increase weighting of canary traffic weight
        - pause: { duration: 30s }
        - setCanaryScale:
            weight: 75 # increase weighting of canary traffic weight
        - pause: { duration: 30s }
        # Argo Rollouts will now take this to 100%
  {{ else }}
  {{ with .Values.strategy }}
  strategy:
  {{- toYaml . | nindent 4 }}
  {{ end }}
  {{ end }}  
  selector:
    matchLabels:
      {{- include "vpconsumer-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: vpconsumer-service    
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vpconsumer-service.selectorLabels" . | nindent 8 }}
        {{- $identity := printf "%s-%s" "aib" $fullName  -}}
        {{ if .Values.aadPodIdentity.enabled  }}
        aadpodidbinding: {{ .Values.aadPodIdentity.identity | default $identity }}
        {{ end }}        
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.serviceAccount.create }}
      serviceAccountName: "sa-{{ include "vpconsumer-service.serviceAccountName" . }}"
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        env:   
          {{- toYaml .Values.containers.env | nindent 10 }}
        envFrom:
          {{- toYaml .Values.containers.envFrom | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{ if .Values.repositories.app }}
        image: "{{ .Values.repositories.app }}/{{ .Values.image.namespace }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{ else }}
        image: "{{ .Values.image.namespace }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{ end }}
        
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.containers.ports }}
        ports:
          {{- toYaml . | nindent 10 }}
        {{ end }}
        {{ if .Values.containers.healthEndpoints.enabled }}
        {{- with .Values.containers.healthEndpoints.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{ end }}
        {{- with .Values.containers.healthEndpoints.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
          {{ end }}
        {{ end }}        
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        {{if .Values.volumeMounts}}   
        volumeMounts:
          {{- with .Values.volumeMounts }}        
            {{- toYaml . | nindent 10 }}
          {{- end }}        
        {{ end }}
        
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      
